var fw_storymap = {
	"tricks":["&ldquo;Tricks&rdquo;",[["SoFurry","https://www.sofurry.com/view/834101"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/tricks"]]],
	"have_some_fun_tonight":["&ldquo;Have Some Fun Tonight&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/have-some-fun-tonight"]]],
	"but_what_a_thrill":["&ldquo;But What a Thrill!&rdquo;",[["SoFurry","https://www.sofurry.com/view/1222653"]]],
	"secrets":["&ldquo;Secrets&rdquo;",[["SoFurry","https://www.sofurry.com/view/1350821"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/secrets"]]],
	"so_frantically_hectic":["&ldquo;So Frantically Hectic&rdquo;",[["SoFurry","https://www.sofurry.com/view/1384062"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/so-frantically-hectic"]]],
	"high_society":["&ldquo;High Society&rdquo;",[["SoFurry","https://www.sofurry.com/view/1452165"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/high-society"]]],
	"partners":["&ldquo;Partners&rdquo;",[["SoFurry","https://www.sofurry.com/view/1465143"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/partners"]]],
	"a_day_in_the_life":["&ldquo;A Day in the Life&rdquo;",[["SoFurry","https://www.sofurry.com/view/1487060"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/day-life"]]],
	"closure":["&ldquo;Closure&rdquo;",[["SoFurry","https://www.sofurry.com/view/1508521"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/closure"]]],
    "the_trouble_with_coyotes":["<em>The Trouble With Coyotes</em>",[["SoFurry","https://www.sofurry.com/view/1102191"]]],
    "the_hot_equations":["&ldquo;The Hot Equations&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/hot-equations"]]],
    "straighten_up_and_fly_right":["&ldquo;Straighten Up and Fly Right&rdquo;",[["SoFurry","https://www.sofurry.com/view/1210932"]]],
    "you_are_leaving_the_american_sector":["&ldquo;You Are Leaving the American Sector&rdquo;",[["SoFurry","https://www.sofurry.com/view/306184"]]],
    "s1e1":["&ldquo;Last Chances&rdquo;",[["SoFurry","https://www.sofurry.com/view/822973"]]],
    "s1e2":["&ldquo;Risk and Reward&rdquo;",[["SoFurry","https://www.sofurry.com/view/824485"]]],
    "s1e3":["&ldquo;Madison May of the Star Patrol!&rdquo;",[["SoFurry","https://www.sofurry.com/view/827655"]]],
    "s1e4":["&ldquo;In Case of Emergency&rdquo;",[["SoFurry","https://www.sofurry.com/view/852137"]]],
    "s1e5":["&ldquo;Biological Distinctiveness&rdquo;",[["SoFurry","https://www.sofurry.com/view/867241"]]],
    "s1e6":["&ldquo;First Impressions&rdquo;",[["SoFurry","https://www.sofurry.com/view/988855"]]],
    "s2e1":["&ldquo;The Machine Stops&rdquo;",[["SoFurry","https://www.sofurry.com/view/1149535"]]],
    "s2e2":["&ldquo;The Diplomatic Affair&rdquo;",[["SoFurry","https://www.sofurry.com/view/1162446"]]],
    "s2e3":["&ldquo;Resistance&rdquo;",[["SoFurry","https://www.sofurry.com/view/1185532"]]],
    "s2e4":["&ldquo;Rendezvous, Part I&rdquo;",[["SoFurry","https://www.sofurry.com/view/1193008"]]],
    "s2e5":["&ldquo;Rendezvous, Part II&rdquo;",[["SoFurry","https://www.sofurry.com/view/1200492"]]],
    "s3e1":["&ldquo;Shared Experience&rdquo;",[["SoFurry","https://www.sofurry.com/view/1308415"]]],
    "s3e2":["&ldquo;Two Birds&rdquo;",[["SoFurry","https://www.sofurry.com/view/1318379"]]],
    "s3e3":["&ldquo;Prophecies, Part I&rdquo;",[["SoFurry","https://www.sofurry.com/view/1327754"]]],
    "s3e4":["&ldquo;Prophecies, Part II&rdquo;",[["SoFurry","https://www.sofurry.com/view/1337298"]]],
    "keep_the_wings":["&ldquo;Keep the Wings Level and True&rdquo;",[["SoFurry","https://www.sofurry.com/view/1429012"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/keep-wings-level-and-true"]]],
    "reckless":["&ldquo;Reckless&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/reckless"]]],
    "dog_star":["&ldquo;Dog Star&rdquo;",[["SoFurry","https://www.sofurry.com/view/285769"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/dog-star"]]],
    "the_odds":["&ldquo;The Odds&rdquo;",[["SoFurry","https://www.sofurry.com/view/843055"]]],
    "behold_i_send_you_forth":["&ldquo;Behold, I Send You Forth&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/behold-i-send-you-forth"]]],
    "shantih":["&ldquo;Shantih&rdquo;",[["SoFurry","https://www.sofurry.com/view/1434250"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/shantih"]]],
    "working_like_a_dog":["&ldquo;Workin' Like a Dog&rdquo;",[["SoFurry","https://www.sofurry.com/view/597929"]]],
}