var fw_storymap = {
    //Casey and Dev stories here
	"tricks":["&ldquo;Tricks&rdquo;",[["SoFurry","https://www.sofurry.com/view/834101"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/tricks"]]],
	"have_some_fun_tonight":["&ldquo;Have Some Fun Tonight&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/have-some-fun-tonight"]]],
	"but_what_a_thrill":["&ldquo;But What a Thrill!&rdquo;",[["SoFurry","https://www.sofurry.com/view/1222653"]]],
	"secrets":["&ldquo;Secrets&rdquo;",[["SoFurry","https://www.sofurry.com/view/1350821"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/secrets"]]],
	"so_frantically_hectic":["&ldquo;So Frantically Hectic&rdquo;",[["SoFurry","https://www.sofurry.com/view/1384062"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/so-frantically-hectic"]]],
	"high_society":["&ldquo;High Society&rdquo;",[["SoFurry","https://www.sofurry.com/view/1452165"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/high-society"]]],
	"partners":["&ldquo;Partners&rdquo;",[["SoFurry","https://www.sofurry.com/view/1465143"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/partners"]]],
	"a_day_in_the_life":["&ldquo;A Day in the Life&rdquo;",[["SoFurry","https://www.sofurry.com/view/1487060"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/day-life"]]],
	"closure":["&ldquo;Closure&rdquo;",[["SoFurry","https://www.sofurry.com/view/1508521"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/closure"]]],
    "the_trouble_with_coyotes":["<em>The Trouble With Coyotes</em>",[["SoFurry","https://www.sofurry.com/view/1102191"]]],
    "changes":["&ldquo;Changes&rdquo;",[["SoFurry","https://www.sofurry.com/view/1511550"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/changes"]]],
    "inhibitions":["&ldquo;Inhibitions&rdquo;",[["SoFurry","https://www.sofurry.com/view/1560783"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/inhibitions"]]],
    "shore_leave":["&ldquo;Shore Leave&rdquo;",[["SoFurry","https://www.sofurry.com/view/1560783"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/shore-leave"]]],
    
    //Star Patrol stories here
    "s1e1":["&ldquo;Last Chances&rdquo;",[["SoFurry","https://www.sofurry.com/view/822973"]]],
    "s1e2":["&ldquo;Risk and Reward&rdquo;",[["SoFurry","https://www.sofurry.com/view/824485"]]],
    "s1e3":["&ldquo;Madison May of the Star Patrol!&rdquo;",[["SoFurry","https://www.sofurry.com/view/827655"]]],
    "s1e4":["&ldquo;In Case of Emergency&rdquo;",[["SoFurry","https://www.sofurry.com/view/852137"]]],
    "s1e5":["&ldquo;Biological Distinctiveness&rdquo;",[["SoFurry","https://www.sofurry.com/view/867241"]]],
    "s1e6":["&ldquo;First Impressions&rdquo;",[["SoFurry","https://www.sofurry.com/view/988855"]]],
    "s2e1":["&ldquo;The Machine Stops&rdquo;",[["SoFurry","https://www.sofurry.com/view/1149535"]]],
    "s2e2":["&ldquo;The Diplomatic Affair&rdquo;",[["SoFurry","https://www.sofurry.com/view/1162446"]]],
    "s2e3":["&ldquo;Resistance&rdquo;",[["SoFurry","https://www.sofurry.com/view/1185532"]]],
    "s2e4":["&ldquo;Rendezvous, Part I&rdquo;",[["SoFurry","https://www.sofurry.com/view/1193008"]]],
    "s2e5":["&ldquo;Rendezvous, Part II&rdquo;",[["SoFurry","https://www.sofurry.com/view/1200492"]]],
    "s3e1":["&ldquo;Shared Experience&rdquo;",[["SoFurry","https://www.sofurry.com/view/1308415"]]],
    "s3e2":["&ldquo;Two Birds&rdquo;",[["SoFurry","https://www.sofurry.com/view/1318379"]]],
    "s3e3":["&ldquo;Prophecies, Part I&rdquo;",[["SoFurry","https://www.sofurry.com/view/1327754"]]],
    "s3e4":["&ldquo;Prophecies, Part II&rdquo;",[["SoFurry","https://www.sofurry.com/view/1337298"]]],
    "s4e1":["&ldquo;Homecoming, Part I&rdquo;",[["SoFurry","https://www.sofurry.com/view/1388877"]]],
    "s4e2":["&ldquo;Homecoming, Part II&rdquo;",[["SoFurry","https://www.sofurry.com/view/1393081"]]],
    "s4e3":["&ldquo;Salvage&rdquo;",[["SoFurry","https://www.sofurry.com/view/1513643"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/s4e3-salvage"]]],
    "s4e4":["&ldquo;Responsibility to Protect&rdquo;",[["SoFurry","https://www.sofurry.com/view/1530370"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/s4e4-responsibility-protect"]]],
    "s4e5":["&ldquo;Agendas&rdquo;",[["SoFurry","https://www.sofurry.com/view/1539089"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/s4e5-agendas"]]],
    "s5e1":["&ldquo;Intruders&rdquo;",[["SoFurry","https://www.sofurry.com/view/1547546"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/s5e1-intruders"]]],
    "s5e2":["&ldquo;The Home Front&rdquo;",[["SoFurry","https://www.sofurry.com/view/1559633"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/s5e2-home-front"]]],
    "s5e3":["&ldquo;Cultural Exchange&rdquo;",[["SoFurry","https://www.sofurry.com/view/1565103"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/s5e3-cultural-exchange"]]],
    "blinded_by_the_light":["&ldquo;Blinded By the Light&rdquo;",[["SoFurry","https://www.sofurry.com/view/1169594"]]],
    
    //Cannon Shoals stories begin here
    "picture_perfect_memories":["&ldquo;Picture Perfect Memories&rdquo;",[["SoFurry","https://www.sofurry.com/view/1319970"]]],
    "no_place_like_home":["&ldquo;No Place Like Home for the Holidays&rdquo;",[["SoFurry","https://www.sofurry.com/view/597929"]]],
    "one_for_the_road":["&ldquo;One More for the Road&rdquo;",[["SoFurry","https://www.sofurry.com/view/966903"]]],
    "smalltownlies":["&ldquo;Small-Town Lies&rdquo;",[["SoFurry","https://www.sofurry.com/view/1049718"]]],
    "friendofthedevil":["&ldquo;Friend of the Devil&rdquo;",[["SoFurry","https://www.sofurry.com/view/1051901"]]],
    "consequences":["&ldquo;Consequences&rdquo;",[["SoFurry","https://www.sofurry.com/view/1077007"]]],
    "favors":["&ldquo;Favors&rdquo;",[["SoFurry","https://www.sofurry.com/view/1090621"]]],
    "graceland":["&ldquo;Graceland&rdquo;",[["SoFurry","https://www.sofurry.com/view/1373541"]]],
    "a_few_minutes_of_darkness":["&ldquo;Graceland&rdquo;",[["SoFurry","https://www.sofurry.com/view/1228923"]]],
    "that_m_word":["&ldquo;That 'M'-Word&rdquo;",[["SoFurry","https://www.sofurry.com/view/753065"]]],
    "paleontology_of_regret":["&ldquo;The Paleontology of Regret&rdquo;",[["SoFurry","https://www.sofurry.com/view/1549530"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/paleontology-regret"]]],
    "through_great_cloudy_skies":["&ldquo;Through Great Cloudy Skies&rdquo;",[["SoFurry","https://www.sofurry.com/view/1568802"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/through-great-cloudy-skies"]]],


    //Moreauverse stories begin here
    "swinging_on_a_star":["&ldquo;Swingin' On a Star&rdquo;",[["SoFurry","https://www.sofurry.com/view/799867"]]],
    "hatikvah":["<em>Hatikvah</em>",[["SoFurry","https://www.sofurry.com/browse/folder/stories?by=123686&folder=65555"]]],
	"steel_and_fire_and_stone":["<em>Hatikvah</em>",[["SoFurry","https://www.sofurry.com/browse/folder/stories?by=123686&folder=25214"]]],
    "cry_havoc_1":["<em>Hatikvah</em>",[["SoFurry","https://www.sofurry.com/browse/folder/stories?by=123686&folder=19161"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/cry-havoc-chapter-1-and-what-rough-beast"]]],
    "bad_dog":["&ldquo;Bad Dog!&rdquo;",[["SoFurry","https://www.sofurry.com/view/316964"]]],
    "shantih":["&ldquo;Shantih&rdquo;",[["SoFurry","https://www.sofurry.com/view/1434250"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/shantih"]]],

    //Brave New World stories go here
    "there_shall_be_wings":["<em>There Shall Be Wings</em>",[["SoFurry","https://www.sofurry.com/browse/folder/stories?by=123686&folder=53225"]]],
    "high_stakes":["&ldquo;High Stakes&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/high-stakes"],["Bodies in Motion","https://www.sofurry.com/view/975603"]]],
    "irr_1":["&ldquo;Gotta Take It Like You Find It&rdquo;",[["SoFurry","https://www.sofurry.com/view/779283"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/iron-road-running-ch-1-gotta-take-it-you-find-it"]]],
    "irr_2":["&ldquo;Ain't Nothin' But My Hammer&rdquo;",[["SoFurry","https://www.sofurry.com/view/786874"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/iron-road-running-ch2-aint-nothin-my-hammer"]]],
    "irr_3":["&ldquo;And She's Known Quite Well By All&rdquo;",[["SoFurry","https://www.sofurry.com/view/795042"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/iron-road-running-ch2-and-shes-known-quite-well-all"]]],
    "irr_4":["&ldquo;Shovel On a Little More Coal&rdquo;",[["SoFurry","https://www.sofurry.com/view/800380"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/iron-road-running-ch-4-shovel-little-more-coal"]]],
    "tn_1":["&ldquo;Storm Warnings&rdquo;",[["SoFurry","https://www.sofurry.com/view/551748"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/terra-nova-ch-1-storm-warnings"]]],
    "tn_2":["&ldquo;A Grey Dawn Breaking&rdquo;",[["SoFurry","https://www.sofurry.com/view/554170"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/terra-nova-ch-2-grey-dawn-breaking"]]],
    "tn_3":["&ldquo;Red Sky at Morning&rdquo;",[["SoFurry","https://www.sofurry.com/view/560248"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/terra-nova-ch-3-red-sky-morning"]]],


    //Miscellaneous stories here
    "that_hard_six":["&ldquo;That Hard Six&rdquo;",[["SoFurry","https://www.sofurry.com/view/680503"]]],
    "points_east":["&ldquo;Points East&rdquo;",[["SoFurry","https://www.sofurry.com/view/534886"]]],
    "fieldwork":["&ldquo;Fieldwork&rdquo;",[["SoFurry","https://www.sofurry.com/view/413873"]]],
    "points_east":["&ldquo;Points East&rdquo;",[["SoFurry","https://www.sofurry.com/view/534886"]]],
    "young_americans":["&ldquo;Young Americans&rdquo;",[["SoFurry","https://www.sofurry.com/view/830072"]]],
    "the_milk_of_paradise":["&ldquo;The Milk of Paradise&rdquo;",[["SoFurry","https://www.sofurry.com/view/1356866"]]],
    "the_hot_equations":["&ldquo;The Hot Equations&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/hot-equations"]]],
    "straighten_up_and_fly_right":["&ldquo;Straighten Up and Fly Right&rdquo;",[["SoFurry","https://www.sofurry.com/view/1210932"]]],
    "perfidia":["&ldquo;Perfidia&rdquo;",[["SoFurry","https://www.sofurry.com/view/1515851"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/perfidia"]]],
    "you_are_leaving_the_american_sector":["&ldquo;You Are Leaving the American Sector&rdquo;",[["SoFurry","https://www.sofurry.com/view/306184"]]],    "keep_the_wings":["&ldquo;Keep the Wings Level and True&rdquo;",[["SoFurry","https://www.sofurry.com/view/1429012"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/keep-wings-level-and-true"]]],
    "reckless":["&ldquo;Reckless&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/reckless"]]],
    "dog_star":["&ldquo;Dog Star&rdquo;",[["SoFurry","https://www.sofurry.com/view/285769"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/dog-star"]]],
    "the_odds":["&ldquo;The Odds&rdquo;",[["SoFurry","https://www.sofurry.com/view/843055"]]],
    "behold_i_send_you_forth":["&ldquo;Behold, I Send You Forth&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/behold-i-send-you-forth"]]],
    "bishop_takes_queens_pawn":["&ldquo;Bishop Takes Queen's Pawn&rdquo;",[["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/bishop-takes-queens-pawn"]]],
    "working_like_a_dog":["&ldquo;Workin' Like a Dog&rdquo;",[["SoFurry","https://www.sofurry.com/view/597929"]]],
    "monday_morning_rail":["&ldquo;Monday Morning Rail&rdquo;",[["SoFurry","https://www.sofurry.com/view/321538"],["Writing Dot Dog","https://www.writing.dog/index.php/writing-overview/library/monday-morning-rail"]]],
}

/* Short story template:
"NAME":["&ldquo;NAME&rdquo;",[["SoFurry","SOFURRYURL"],["Writing Dot Dog","writingdogurl"]]],

*/